export { default as About } from './about/About';
export { default as Footer } from './footer/Footer';
export { default as Hero } from './hero/Hero';
export { default as Product } from './product/Product';
export { default as Discount } from './discount/Discount';
export { default as Navbar } from './navbar/Navbar';
export { default as Fav } from './fav/Fav';
export { default as Mobile } from './mobile/Mobile';
export { default as Brands } from './brands/Brands';
